name: Vehicle Service CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Basic server check
      run: |
        cd backend
        node -e "require('./server.js')"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd vehicleservicemanagement-master

          # Pull latest code
          git pull origin main

          # Install backend dependencies
          cd backend
          npm install

          # Restart server
          pm2 restart server || pm2 start server.js --name server